### ISSUE TITLE
Convert rdf raw nodes

### ISSUE THREAD

**Issue by oeway** [bioimage-io/bioengine-model-runner#8]
Hi @FynnBe We are having an issue for the model in the BioEngine (`straightforward-crocodile`), the model RDF is written in version 0.3 and I loaded it as raw nodes, but when we check it [here](https://github.com/bioimage-io/core-bioimage-io-python/blob/70d681c42f508a97d3e2f0814273033c6827d7e7/bioimageio/core/prediction_pipeline/_prediction_pipeline.py#L108) we try to use the `'bioimageio.spec.model.v0_4.raw_nodes.Model'` and it failed (since its type = `<class 'bioimageio.spec.model.v0_3.raw_nodes.Model'>`).

In this case, what would you suggest? Maybe we should auto-convert the raw model resource before feeding into the pipeline? What function can we call?

**Comment by FynnBe** [comment]
you most likely call `load_raw_resource_description` without setting `update_format=="latest"`
https://github.com/bioimage-io/spec-bioimage-io/blob/8161db4b0873a571a94de419732dacacb5dba9f3/bioimageio/spec/io_.py#L129-L132

With `update_format=="latest"` autoconversion will be applied. core always works with 'latest' 

side note: this reminds me of the problem of installing older core versions. I made this PR to address that: https://github.com/bioimage-io/core-bioimage-io-python/pull/306

**Comment by oeway** [comment]
Great! Thanks! I will try that!
